[tools]
"java" = { version = "openjdk-21", release_type = "ga" }

[tasks.test]
description = "Run automated tests"
run = "./gradlew test"

[tasks.check]
description = "Run compilation checks"
run = "./gradlew check --parallel"

[tasks.build]
description = "Build Docker image with local plugin"
run = [
  "./gradlew shadowJar",
  "docker build -t kestra-custom ."
]

[tasks.up]
description = "Run the Docker image"
run = """
docker run --rm -p 8080:8080 \
    -v ~/.keys/kestra-development-sa.json:/run/secrets/gcp_demo_sa.json \
    -e GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/gcp_demo_sa.json \
    kestra-custom server local
"""